name: CS Fixer

on: [push, pull_request]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: sebastianks/php-cs-fixer-ga@v0.0.1
        with:
          args: --verbose .
